---
title: "Weiheng_Chen_HW3"
author: "Weiheng Chen""001802389"
date: "October 11, 2019"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(magrittr)
#Import dataset-airline_delay
setwd("C:\\Users\\weihe\\OneDrive\\Desktop\\IE6600\\Assigenment3")
df1 <- read.csv("airline_delay.csv", sep=",", stringsAsFactors = FALSE)

# 1 Plot the bar plot as shown below. The y axis is "carrier name", the x axis is the "total arrival delay" (sum of arr_delay column) for the entire data set. (10 points)
df1_1 <- df1 %>%
    group_by(carrier_name)%>%
    summarise(total.arrival.delay = sum(arr_delay, na.rm = TRUE))%>%
    arrange(desc(total.arrival.delay))

ggplot(df1_1, aes(x = reorder(carrier_name, total.arrival.delay), y = total.arrival.delay)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    xlab("Carrier Name") + ylab("Total Arrival Delay")
```

```{r}
# 2 Plot the stack bar plot as shown below. 
#   The y axis is "carrier name", the x axis is the "total arrival delay" (sum of arr_delay column) for the entire data set.
#   The stacks represent the variable year. (10 points)
df1_2 <- df1 %>%
    group_by(carrier_name, year)%>%
    summarise(total.arrival.delay = sum(arr_delay, na.rm = TRUE))%>%
    arrange(desc(total.arrival.delay))
ggplot(df1_2, aes(reorder(factor(carrier_name), total.arrival.delay), y = total.arrival.delay, fill = factor(year))) + 
    geom_bar(stat = "identity") + 
    coord_flip() +
    labs(x = "Carrier Name", y = "Total Arrival Delay", fill="Year")
```

```{r}
# 3 Plot the following heat map.
#   The y axis should contain only the airports shown in the figure below.
#   The x axis represents the "year". 
#   The heat map color should represent "total arrival delay" (sum of arr_delay column). (10 points)
df1_3 <- df1 %>%
    group_by(airport, year)%>%
    summarize(total.arrival.delay = sum(arr_delay, na.rm = TRUE))%>%
    filter(airport %in% c('SFO', 'ORD', 'LGA', 'LAX', 'JFK', 'EWR', 'DFW', 'DEN', 'BOS', 'AFL'))
ggplot(df1_3, aes(x=factor(year), y=factor(airport), fill=total.arrival.delay)) +
    geom_tile() +
    labs(x = "Year", y = "Airport Name", fill="Total Arrival Delay")
```

```{r}
# 4 Plot the following line plot (10 points)
library(tidyr)
df1_4 <- df1 %>%
    select(year, carrier_delay, late_aircraft_delay)%>%
    group_by(year)%>%
    summarise(carrier_delay = sum(carrier_delay, na.rm = TRUE), 
              late_aircraft_delay = sum(late_aircraft_delay, na.rm = TRUE))%>%
    gather(key = "Delay_Type", value = "Mins", carrier_delay, late_aircraft_delay)
ggplot(df1_4, aes(x = year, y= Mins, group = Delay_Type, color = Delay_Type)) +
      geom_line() + geom_point()+
      labs(x = "Year", y = "Mins")
```

```{r}
# 5 Plot the following distributions (30 points)
# Box Plot
df1_5 <- df1 %>%
    filter(airport %in% c('JFK', 'BOS', 'ATL'))
ggplot(df1_5, aes(x = factor(airport), y = arr_delay)) + 
    geom_boxplot()+
    labs(x = "Airport", y = "Arrival Delay Mins")
```
```{r}
# Violin Plot
ggplot(df1_5, aes(x = factor(airport), y = arr_delay)) + 
    geom_violin()+
    labs(x = "Airport", y = "Arrival Delay Mins")
```
```{r}
# Density Plot
ggplot(df1_5, aes(x = arr_delay, fill = airport)) +
    geom_density(alpha=0.4)+
    labs(x = "Arrival Delay (mins)", y = "Density")
```

```{r}
# 6 Answer the following (30 points)
# The link below gives the data for passengers enplanement. Enplanement is the term used for passenger boarding.
library(readxl)
df2 <- read_excel("cy17-commercial-service-enplanements.xlsx")
# Create a new table as follows:
df2_1 <- df2%>%group_by(Airport=Locid)%>%
    summarise(Enplanement =`CY 17 Enplanements`)
df1_6 <- df1%>%filter(year == "2017")%>%
    group_by(Airport = airport)%>%
    summarise(`Arrival Delay (mins)`= sum(arr_delay,na.rm=TRUE))
df2_2 <- merge(df2_1,df1_6,by="Airport")
View(df2_2)
```
```{r}
# Plot a scatter plot with enplanement on x axis and arrival delay in y axis.
ggplot(df2_2, aes(Enplanement, `Arrival Delay (mins)`))+
    geom_point()+
    theme_update(text = element_text(size=16))
```
```{r}
# Plot the same figure above with x and y axis in log scale.
library(scales)
ggplot(df2_2, aes(Enplanement, `Arrival Delay (mins)`)) + geom_point() +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    theme_bw() +theme_update(text = element_text(size=16))
```

